### PR TITLE
fix task poll NPE

### LINKED ISSUE #1477: NPE when worker queue is empty
I have upgraded to v2.23.0 and started using `TaskRunnerConfigurer` instead of deprecated `WorkflowTaskCoordinator` for workers. However when there is nothing to poll I get NPE in the log.

`ERROR c.n.c.c.automator.TaskPollExecutor - Error when polling for tasks
java.lang.NullPointerException: null
	at com.netflix.conductor.client.http.TaskClient.populateTaskInput(TaskClient.java:176)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:125)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$0(TaskPollExecutor.java:101)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:42)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:101)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$null$0(TaskRunnerConfigurer.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	
...`

Newly used GET of `tasks/poll/{taskType}` returns 204 instead of previously used batch poll that returned 200. That leads to throwing `com.sun.jersey.api.client.UniformInterfaceException` in `
com.netflix.conductor.client.http.ClientBase#getForEntity(java.lang.String, java.lang.Object[], java.util.function.Function<com.sun.jersey.api.client.ClientResponse,T>, java.lang.Object...)`. 

Then task in `com.netflix.conductor.client.http.TaskClient#pollTask` ends up being null and `populateTaskInput` method ends up with NPE as stated above.

Not much really happens as catch block in `com.netflix.conductor.client.automator.TaskPollExecutor#pollAndExecute` handles the NPE, but log is full of errors and TaskPollErrorCount is all wrong.

### PR DESCRIPTION
**Pull request by apanicker-nflx**
Closes #1477

### CODE REVIEW

File: client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java [hunk 1]
```diff
@@ -166,14 +164,45 @@ public void testTaskPollException() {
...
+
+        Worker worker = mock(Worker.class);
+        when(worker.getPollingInterval()).thenReturn(3000);
+        when(worker.getTaskDefName()).thenReturn("test");
+        when(worker.execute(any())).thenReturn(new TaskResult(task));
+
+        TaskClient taskClient = Mockito.mock(TaskClient.class);
+        when(taskClient.pollTask(any(), any(), any()))
+            .thenReturn(new Task())
+            .thenReturn(task);
```
Comment (kishorebanala) [inline client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java]: Is it intentional to have two `thenReturn` statements?

Comment (apanicker-nflx) [reply client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java]: yes, these will be the values returned by this method on 2 consecutive invocations.
